feat: add edit/delete features
Nidal-Marwan/Via-Training pull request #35
Opened 2022-06-28 09:12 UTC by nidalhjab

- Add edit/delete buttons to the locations table with their functionalities.
- Add LoginModal and LocationModal with custom styles.
- Edit the table components to be reused in the modal.

2022-06-28 09:19 UTC, mohannadjamal requested changes

2022-06-28 09:19 UTC, mohannadjamal commented on packages/client/public/assets/locales/en/translation.json
> +			"decline": "Cancle"
Cancel typo

2022-06-28 09:19 UTC, mohannadjamal commented on packages/client/src/common/components/Modal/LocationModal.tsx
> +const ModalBox = styled(Box)({
Preferably styled constants should be in LocationModal.styles.ts

2022-06-28 10:59 UTC, hamzahmurrar commented on packages/client/src/common/components/Map/Map.tsx
> +}
fix indentation

2022-06-28 10:59 UTC, hamzahmurrar commented on packages/client/src/common/components/Map/Map.tsx
> +		if(event){
`if (event) {`

2022-06-28 11:59 UTC, mohannadjamal approved these changes

2022-06-30 07:23 UTC, nidalhjab commented
> fix conflicts please

already fixed @hamzahmurrar

2022-06-30 08:01 UTC, hamzahmurrar approved these changes

2022-06-30 08:02 UTC, merged